-- Таблица для отслеживания активных пользователей (Presence)
create table if not exists public.presence (
  id bigint generated by default as identity primary key,
  peer_id text not null,
  room_id text not null,
  username text not null,
  updated_at timestamptz default now(),
  unique(peer_id, room_id)
);

-- Индекс для быстрого поиска по комнатам
create index if not exists idx_presence_room on public.presence(room_id);
create index if not exists idx_presence_updated on public.presence(updated_at);

-- Таблица для истории сообщений (опционально, если нужна персистентность)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id text not null,
  sender text not null,
  content text not null,
  created_at timestamptz default now()
);

create index if not exists idx_messages_room on public.messages(room_id);

-- RLS Policies (Безопасность)
alter table public.presence enable row level security;
alter table public.messages enable row level security;

-- Разрешить всем читать и писать в presence (для демо)
create policy "Allow all operations on presence" on public.presence
  for all using (true) with check (true);

create policy "Allow all operations on messages" on public.messages
  for all using (true) with check (true);

-- Функция очистки старых записей presence (запускается вручную или триггером)
-- Для простоты очистку можно делать на клиенте или через Scheduled Edge Function
